"""
Calibration reference implementation matching contracts/src/ScoringEngine.sol §7.4.2.

Storage layout (per agent per category):
    bucket_accuracy[10] : int256, 1e6-scaled fractional accuracy ∈ [0, 1e6]
    bucket_count[10]    : uint256, raw counts

Per-call update (on each resolution):
    bucket_idx = confidence_bps // 1000                          (∈ [0, 9])
    realized_scaled = (score + 1_000_000) // 2                   (∈ [0, 1e6])
    bucket_accuracy[bucket_idx]
        = (9 * bucket_accuracy[bucket_idx] + realized_scaled) // 10
    bucket_count[bucket_idx] += 1

Calibration on read:
    total_count = Σ bucket_count[i]
    if total_count < 10: return 0   # cold start; UI shows "calibrating"
    For each i in 0..9:
        midpoint_scaled = i * 100_000 + 50_000     (∈ [50_000, 950_000])
        diff           = midpoint_scaled - bucket_accuracy[i]
        sq             = diff * diff               (∈ [0, ~1e12])
        sum_weighted_sq += sq * bucket_count[i]
    cal_score = -((sum_weighted_sq * 4) // (total_count * 1_000_000))
    clamp to [-1_000_000, 0]

Run:
    python calibration_reference.py
"""

SCALE = 1_000_000
ALPHA_NUM = 1
ALPHA_DEN = 10
CAL_MIN = -1_000_000
CAL_MAX = 0


def realized_scaled(score: int) -> int:
    """Map signed score ∈ [-1e6, 1e6] to scaled realized accuracy ∈ [0, 1e6]."""
    return (score + SCALE) // 2


def ema_update(old_scaled: int, realized: int) -> int:
    """EMA with α = 0.1 in 1e6-scaled integer space: new = (9*old + realized) // 10."""
    return ((ALPHA_DEN - ALPHA_NUM) * old_scaled + ALPHA_NUM * realized) // ALPHA_DEN


def calibration_score(bucket_accuracy, bucket_count) -> int:
    """Compute calibration score from current bucket state. Both inputs length-10."""
    assert len(bucket_accuracy) == 10 and len(bucket_count) == 10
    total = sum(bucket_count)
    if total < 10:
        return 0
    sum_weighted_sq = 0
    for i in range(10):
        midpoint = i * 100_000 + 50_000
        diff = midpoint - bucket_accuracy[i]
        sq = diff * diff
        sum_weighted_sq += sq * bucket_count[i]
    cal = -((sum_weighted_sq * 4) // (total * SCALE))
    if cal < CAL_MIN:
        cal = CAL_MIN
    if cal > CAL_MAX:
        cal = CAL_MAX
    return cal


# ---- Test cases ----

def _b(b5_acc, b5_cnt):
    """Helper: single-bucket-5 state."""
    acc = [0] * 10
    cnt = [0] * 10
    acc[5] = b5_acc
    cnt[5] = b5_cnt
    return acc, cnt


def _perfect_calibration():
    return [i * 100_000 + 50_000 for i in range(10)], [10] * 10


def _overconfident():
    # Low confidence buckets near midpoint, high-confidence buckets stuck low.
    acc = [50_000, 150_000, 250_000, 350_000, 450_000, 200_000, 200_000, 200_000, 200_000, 200_000]
    cnt = [2, 2, 2, 2, 2, 10, 10, 10, 10, 10]
    return acc, cnt


def _underconfident():
    # High confidence buckets near midpoint, low-confidence buckets actually high accuracy.
    acc = [800_000, 800_000, 800_000, 800_000, 800_000, 550_000, 650_000, 750_000, 850_000, 950_000]
    cnt = [10, 10, 10, 10, 10, 2, 2, 2, 2, 2]
    return acc, cnt


def _mixed_realistic():
    acc = [40_000, 140_000, 220_000, 300_000, 420_000, 550_000, 680_000, 770_000, 880_000, 920_000]
    cnt = [5, 8, 12, 15, 18, 20, 15, 10, 8, 5]
    return acc, cnt


CASES = [
    # (label, bucket_accuracy, bucket_count)
    ("cold_start",                          [0] * 10, [0] * 10),                 # 1: total=0 → 0
    ("one_resolution_below_min",            *_b(500_000, 1)),                    # 2: total=1 → 0
    ("ten_resolutions_bucket5_perfect",     *_b(500_000, 10)),                   # 3: just qualifies
    ("hundred_resolutions_bucket5_perfect", *_b(500_000, 100)),                  # 4: deep, perfect-for-data
    ("perfectly_calibrated",                *_perfect_calibration()),            # 5: zero penalty
    ("overconfident",                       *_overconfident()),                  # 6: penalty in hi-conf
    ("underconfident",                      *_underconfident()),                 # 7: penalty in lo-conf
    ("mixed_realistic",                     *_mixed_realistic()),                # 8: small mixed
    ("max_miscal_bucket0_high_acc",         [950_000] + [0] * 9, [100] + [0] * 9),  # 9: max squared diff
    ("max_miscal_bucket9_low_acc",          [0] * 9 + [50_000], [0] * 9 + [100]),   # 10: symmetric
]


def main() -> None:
    print("// Auto-generated by calibration_reference.py — do not edit.")
    print()
    expected = []
    for i, (label, acc, cnt) in enumerate(CASES):
        cal = calibration_score(acc, cnt)
        expected.append(cal)
        total = sum(cnt)
        print(f"//   case {i + 1:>2} {label:<40} total={total:>4}  cal={cal}")
    print()
    print("// Expected (Solidity int256 array):")
    print(f"int256[{len(expected)}] memory expected = [")
    for i, v in enumerate(expected):
        comma = "," if i + 1 < len(expected) else ""
        print(f"    int256({v}){comma}")
    print("];")
    print()

    # EMA spot-checks
    print("// EMA update spot-checks (old_scaled, score, realized_scaled, new_scaled):")
    ema_cases = [
        (0,            1_000_000),   # cold + perfect
        (0,                    0),   # cold + neutral
        (0,           -1_000_000),   # cold + worst
        (500_000,      1_000_000),   # mid + perfect
        (1_000_000,   -1_000_000),   # full + worst
    ]
    for old, score in ema_cases:
        r = realized_scaled(score)
        new = ema_update(old, r)
        print(f"//   old={old:>9}  score={score:>9}  realized={r:>9}  new={new:>9}")


if __name__ == "__main__":
    main()
