"""
Range-CRPS reference implementation matching contracts/src/scorers/RangeCrpsScorer.sol exactly.

All arithmetic uses Python integers + // (floor division for non-negatives), which matches
Solidity uint256 + integer division. The Solidity tests hard-code the values printed by this
script and assert exact equality (no tolerance).

Forecast: uniform over [a, b] where a, b are bucket boundaries snapped from (predLow, predHigh).
Outcome: point mass at the midpoint of the outcome bucket.
Domain split into N = 100 equal-width buckets.

Score mapping: score = clamp((1 - 2 * CRPS / D) * 1e6, -1e6, +1e6).

Implementation works in doubled coordinates (a' = 2a, b' = 2b, y' = 2y) to keep the
half-bucket-width midpoint integral.

Run:
    python crps_reference.py
"""

N = 100
SCORE_MAX = 1_000_000
SCORE_MIN = -1_000_000
SCALE = 1_000_000


def bucket_idx(v: int, domain_min: int, domain_max: int, w: int) -> int:
    if v <= domain_min:
        return 0
    if v >= domain_max:
        return N - 1
    idx = (v - domain_min) // w
    if idx >= N:
        idx = N - 1
    return idx


def range_crps_score(
    low_raw: int,
    high_raw: int,
    outcome_raw: int,
    domain_min: int,
    domain_max: int,
) -> int:
    assert domain_max > domain_min, "InvalidDomain"
    D = domain_max - domain_min
    w = D // N
    assert w > 0, "InvalidDomain (w==0)"

    if low_raw > high_raw:
        low_raw, high_raw = high_raw, low_raw

    b_lo = bucket_idx(low_raw, domain_min, domain_max, w)
    b_hi = bucket_idx(high_raw, domain_min, domain_max, w)
    y_bk = bucket_idx(outcome_raw, domain_min, domain_max, w)

    a2 = 2 * (domain_min + b_lo * w)
    b2 = 2 * (domain_min + (b_hi + 1) * w)
    y2 = 2 * domain_min + (2 * y_bk + 1) * w

    if y2 < a2:
        numerator = 3 * (a2 - y2) + (b2 - a2)
        deduction = (SCALE * numerator) // (3 * D)
    elif y2 > b2:
        numerator = 3 * (y2 - b2) + (b2 - a2)
        deduction = (SCALE * numerator) // (3 * D)
    else:
        dya = y2 - a2
        dby = b2 - y2
        dba = b2 - a2
        num = dya**3 + dby**3
        denom = 3 * dba * dba * D
        deduction = (SCALE * num) // denom

    if deduction >= 2 * SCALE:
        sc = SCORE_MIN
    else:
        sc = SCORE_MAX - deduction

    if sc > SCORE_MAX:
        sc = SCORE_MAX
    if sc < SCORE_MIN:
        sc = SCORE_MIN
    return sc


# 10 hand-picked diverse cases. All use domain [0, 10000] (e.g. APR basis points 0..100%).
DM, DX = 0, 10_000
CASES = [
    # (label, low, high, outcome, domainMin, domainMax)
    ("perfect_centered",          2_900, 3_100, 3_000, DM, DX),  # 1
    ("off_by_one_high",           2_900, 3_000, 3_200, DM, DX),  # 2
    ("single_bucket_far_above",       0,    99, 9_999, DM, DX),  # 3
    ("outcome_at_domain_max",     5_000, 5_100, 10_000, DM, DX), # 4
    ("single_bucket_centered",    5_000, 5_000, 5_050, DM, DX),  # 5
    ("full_domain",                   0, 10_000, 5_000, DM, DX), # 6
    ("two_bucket_edge_aligned",   5_000, 5_100, 5_050, DM, DX),  # 7
    ("below_outcome",             2_000, 2_100, 5_000, DM, DX),  # 8
    ("above_outcome",             7_000, 7_100, 5_000, DM, DX),  # 9
    ("inverted_bounds",           5_100, 4_900, 5_000, DM, DX),  # 10 — auto-swapped
]


def main() -> None:
    print(f"// Auto-generated by crps_reference.py — do not edit.")
    print(f"// Domain: [{DM}, {DX}] (N={N} buckets, w={(DX - DM) // N})")
    print()
    print("// solidity:")
    print("// expectedScores = [int256(...), ...];")
    print()
    expected = []
    for i, (label, lo, hi, out, dm, dx) in enumerate(CASES):
        sc = range_crps_score(lo, hi, out, dm, dx)
        expected.append(sc)
        print(f"//   case {i + 1:>2} {label:<28} low={lo:>5} high={hi:>5} out={out:>5} -> score={sc}")
    print()
    print(f"int256[{len(expected)}] memory expected = [")
    for i, v in enumerate(expected):
        comma = "," if i + 1 < len(expected) else ""
        print(f"    int256({v}){comma}")
    print("];")


if __name__ == "__main__":
    main()
